config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home', to: 'page#home'
  get '/recipes', to: 'recipes#index'
  get '/recipes/new', to: 'recipes#new', as: 'new_recipe'
  get 'recipes/:id', to: 'recipes#show', as: 'recipe'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :chefname, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                  format: { with: VALID_EMAIL_REGEX },
                  uniqueness: { case_sensitive: false }

  has_many :recipes                
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 5, maximum: 500 }
  validates :chef_id, presence: true
  belongs_to :chef
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @recipes = Recipe.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav.html.erb
<nav >
  <div class="nav-wrapper">
        <a href="<%= root_path %>" class="brand-logo"><%= image_tag("recipes_logo.svg", :alt => "recipes logo", :height => '50%', :width => '50%', :class => 'nav-logo') %></a>
        <a href="#" data-activates="mobile-menu" class="button-collapse"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="sass.html">Chefs</a></li>
          <li><a href="badges.html">Recipes</a></li>
          <li><a href="collapsible.html">Ingredients</a></li>
          <li><a href="#" data-target="modallogin" >Sign In</a></li>
        </ul>
        <ul class="side-nav" id="mobile-menu">
          <li><a href="sass.html">Chefs</a></li>
          <li><a href="badges.html">Recipes</a></li>
          <li><a href="collapsible.html">Ingredients</a></li>
          <li><a href="mobile.html">Sign In</a></li>
        </ul>
      </div>
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="hero-background">
  <div class="row">
        <div class="col s12 l6 m12">
        <div class="hero-table">
                  <div class="hero">
                  <h1>The best place
                    to share repices</h1></div>
        </div>
          </div>
        <div class="col s12 l6 m12">


                    <div class="card">
                      <div class="card-content">
                        <span class="card-title">SIGN UP NOW</span>
                        <form>
                        <div class="row">
                         <div class="input-field col s12">
                           <input id="chef_name" type="text" class="validate">
                           <label for="chef_name">Chef name</label>
                         </div>
                         <div class="input-field col s12">
                           <input id="email" type="text" class="validate">
                           <label for="email">Email</label>
                         </div>
                         <div class="input-field col s12">
                           <input id="password" type="text" class="validate">
                           <label for="password">Password</label>
                         </div>
                         <div class="input-field col s12">
                           <input id="repeat_password" type="text" class="validate">
                           <label for="repeat_password">Repeat Password</label>
                         </div>
                       </div>
                     </form>


                      </div>
                      <div class="card-action">
                              <button class="btn waves-effect waves-light" type="submit" name="action">Create<i class="material-icons right">send</i></button>
                      </div>
                    </div>
        </div>
    </div>
</div>

<%= render 'shared/recipes'%>

  <div id="modallogin" class="modal">
    <div class="modal-content">
      <form>
      <div class="row">
       <div class="input-field col s12">
         <input id="email" type="text" class="validate">
         <label for="email">Email</label>
       </div>
       <div class="input-field col s12">
         <input id="password" type="text" class="validate">
         <label for="password">Password</label>
       </div>
         <button class="btn waves-effect waves-light" type="submit" name="action">Sign in<i class="material-icons right">send</i></button>
     </div>
   </form>
    </div>
  </div>

  <footer>
    &copy; <%= Date.today.year %> Albo Studio
  </footer>

app/views/recipes/index.html.erb
<div class="row">
<% @recipes.each do |recipe| %>
      <div class="col s12 m4 l3">
        <div class="card-recipe">
          <h4><%= recipe.name %></h4>
          <p><%= recipe.description %></p>
          <span class="card-recipe-chefname"><i class="material-icons">perm_identity</i><%= recipe.chef.chefname %></span>
          <span class="card-recipe-date"><small><%= time_ago_in_words(recipe.created_at) %> ago</small></span>
          <%= link_to recipe_path(recipe), { class: "waves-effect waves-light btn-flat right card-recipe-more" } do %>
              More
          <% end %>
        </div>
      </div>
<% end %>
</div>

app/views/recipes/show.html.erb
<div id="recipe-title-background">
  <div class="row">
        <div class="col s12 l12 m12">
            <div class="hero-table hero-table-middle">
                <div class="hero-recipe">
                      <h1><%= @recipe.name %></h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="recipe-info">
  <div class="row">
    <div class="col s12 l6 m6">
      <h2>About this recipe</h2>
      <div class="line-green"></div>
      <%= @recipe.description %>
    </div>
    <div class="col s12 l6 m6">
      <h2>Created by</h2>
      <div class="line-green"></div>
      <h2 class="green-title"><%= @recipe.chef.chefname %></h2>
      <%= time_ago_in_words(@recipe.created_at) %> ago
    </div>
  </div>
</div>

app/views/shared/_recipes.html.erb
<div class="row">
<% @recipes.each do |recipe| %>
      <div class="col s12 m4 l3">
        <div class="card-recipe">
          <h4><%= recipe.name %></h4>
          <p><%= recipe.description %></p>
          <span class="card-recipe-chefname"><i class="material-icons">perm_identity</i><%= recipe.chef.chefname %></span>
          <span class="card-recipe-date"><small><%= time_ago_in_words(recipe.created_at) %> ago</small></span>
          <%= link_to recipe_path(recipe), { class: "waves-effect waves-light btn-flat right card-recipe-more" } do %>
              More
          <% end %>
        </div>
      </div>
<% end %>
</div>